version: '3.9'

networks:
  netbox_lan:
    name: netbox_lan
    external: true

services:
  netbox:
    build:
      context: .
      dockerfile: Dockerfile
    # image: netbox:latest-plugins
    networks:
      netbox_lan:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.netbox.rule=Host(`netbox.as73.inetsix.net`)"
      - "traefik.http.routers.netbox.entrypoints=web"
      - "traefik.http.services.netbox.loadbalancer.server.port=8080"
      - "traefik.http.routers.api.entrypoints=http"
    ports:
      - 8000:8080
    environment:
      TIME_ZONE: "Europe/Paris"
      # NAPALM_USERNAME: '< set your own NAPALM user >'
      # NAPALM_PASSWORD: '< set your own NAPALM password >'

  netbox-worker:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      netbox_lan:
    environment:
      TIME_ZONE: "Europe/Paris"
  netbox-housekeeping:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      netbox_lan:
    environment:
      TIME_ZONE: "Europe/Paris"
  postgres:
    networks:
      netbox_lan:
    environment:
      TIME_ZONE: "Europe/Paris"
  redis:
    networks:
      netbox_lan:
    environment:
      TIME_ZONE: "Europe/Paris"
  redis-cache:
    networks:
      netbox_lan:
    environment:
      TIME_ZONE: "Europe/Paris"
